<?php

/**
 * @file
 * Contains custom functionality for My Custom Module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function my_custom_module_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'my_custom_module/custom-js';
}

/**
 * Implements hook_theme().
 */
function my_custom_module_theme($existing, $type, $theme, $path) {
  return [
    'my_custom_theme_hook' => [
      'variables' => ['content' => NULL],
      'template' => 'my-custom-template',
    ],
  ];
}
